version: "3"
services:
  aicc-python-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
