---
version: '3'
services:
  aicc-python-api:
    build: .
    container_name: aicc-python-api
    restart: unless-stopped
    volumes:
    - .:/workdir
    environment:
    - TZ=Asia/Jakarta
    command: sh -c "cd /workdir && sudo apt update -y && cat packages.txt | xargs sudo apt install -y && pip install -r requirements.txt && python main.py"
    ports:
    - 0.0.0.0:51323:51323